-- BETA GROUP – Faza 2: evidenca praznikov, dopusta in bolniške
-- Zaženite v Supabase Dashboard -> SQL Editor -> New query.
-- Ustvari novo tabelo; obstoječih zapisov v work_hours ne spreminja.

create table if not exists public.work_absences (
  id bigint generated by default as identity primary key,
  worker_id uuid not null references public.workers(id) on delete cascade,
  absence_type text not null check (absence_type in ('holiday', 'vacation', 'sickness')),
  start_date date not null,
  end_date date not null,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint work_absences_dates_check check (end_date >= start_date)
);

alter table public.work_absences enable row level security;

-- Workers can view their own absence records; admins can view all.
drop policy if exists "work_absences_select_own_or_admin" on public.work_absences;
create policy "work_absences_select_own_or_admin"
on public.work_absences for select to authenticated
using (
  worker_id = auth.uid()
  or exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true)
);

-- Only active administrators may add absence records.
drop policy if exists "work_absences_insert_admin" on public.work_absences;
create policy "work_absences_insert_admin"
on public.work_absences for insert to authenticated
with check (
  created_by = auth.uid()
  and exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true)
);

-- Only active administrators may delete absence records.
drop policy if exists "work_absences_delete_admin" on public.work_absences;
create policy "work_absences_delete_admin"
on public.work_absences for delete to authenticated
using (exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true));

grant select, insert, delete on public.work_absences to authenticated;
grant usage, select on sequence public.work_absences_id_seq to authenticated;
