-- BETA GROUP – Faza 3: ročni vnos nočnih ur in nadur ter administratorsko popravljanje zapisov
-- Zaženite v Supabase Dashboard -> SQL Editor -> New query.
-- Obstoječih zapisov v work_hours ne briše ali spreminja.

create table if not exists public.work_hour_adjustments (
  id bigint generated by default as identity primary key,
  worker_id uuid not null references public.workers(id) on delete cascade,
  month text not null check (month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  night_hours numeric(7,2) not null default 0 check (night_hours >= 0 and night_hours <= 1000),
  overtime_hours numeric(7,2) not null default 0 check (overtime_hours >= 0 and overtime_hours <= 1000),
  note text,
  created_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint work_hour_adjustments_worker_month_unique unique (worker_id, month)
);

alter table public.work_hour_adjustments enable row level security;

drop policy if exists "work_hour_adjustments_select_own_or_admin" on public.work_hour_adjustments;
create policy "work_hour_adjustments_select_own_or_admin"
on public.work_hour_adjustments for select to authenticated
using (
  worker_id = auth.uid()
  or exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true)
);

drop policy if exists "work_hour_adjustments_insert_admin" on public.work_hour_adjustments;
create policy "work_hour_adjustments_insert_admin"
on public.work_hour_adjustments for insert to authenticated
with check (
  created_by = auth.uid()
  and exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true)
);

drop policy if exists "work_hour_adjustments_update_admin" on public.work_hour_adjustments;
create policy "work_hour_adjustments_update_admin"
on public.work_hour_adjustments for update to authenticated
using (exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true))
with check (exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true));

drop policy if exists "work_hour_adjustments_delete_admin" on public.work_hour_adjustments;
create policy "work_hour_adjustments_delete_admin"
on public.work_hour_adjustments for delete to authenticated
using (exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true));

grant select, insert, update, delete on public.work_hour_adjustments to authenticated;
grant usage, select on sequence public.work_hour_adjustments_id_seq to authenticated;

-- Allow active administrators to correct or delete mistaken arrival/departure records.
drop policy if exists "work_hours_admin_update" on public.work_hours;
create policy "work_hours_admin_update"
on public.work_hours for update to authenticated
using (exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true))
with check (exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true));

drop policy if exists "work_hours_admin_delete" on public.work_hours;
create policy "work_hours_admin_delete"
on public.work_hours for delete to authenticated
using (exists (select 1 from public.workers w where w.id = auth.uid() and w.is_admin = true and w.active = true));

grant update, delete on public.work_hours to authenticated;
