create extension if not exists pgcrypto;
create table if not exists public.employees(id uuid primary key default gen_random_uuid(),auth_user_id uuid unique references auth.users(id) on delete set null,name text not null,position text default 'Delavec',phone text,email text,active boolean not null default true,created_at timestamptz default now());
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,employee_id uuid unique references public.employees(id) on delete set null,role text not null default 'worker' check(role in('admin','worker')),full_name text,created_at timestamptz default now());
create table if not exists public.work_records(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete cascade,work_date date not null default current_date,clock_in timestamptz,clock_out timestamptz,total_hours numeric(8,2) default 0,clock_in_lat numeric(10,7),clock_in_lng numeric(10,7),clock_out_lat numeric(10,7),clock_out_lng numeric(10,7),project text,note text,created_at timestamptz default now());
create index if not exists wr_emp_date on public.work_records(employee_id,work_date desc);
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;
create or replace function public.my_employee_id() returns uuid language sql stable security definer set search_path=public as $$select employee_id from public.profiles where id=auth.uid()$$;
create or replace function public.calc_hours() returns trigger language plpgsql as $$begin if new.clock_in is not null and new.clock_out is not null then new.total_hours:=round((extract(epoch from(new.clock_out-new.clock_in))/3600)::numeric,2);else new.total_hours:=0;end if;return new;end;$$;
drop trigger if exists calc_hours_trg on public.work_records; create trigger calc_hours_trg before insert or update of clock_in,clock_out on public.work_records for each row execute function public.calc_hours();
alter table public.employees enable row level security; alter table public.profiles enable row level security; alter table public.work_records enable row level security;
drop policy if exists emp_admin on public.employees; create policy emp_admin on public.employees for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists emp_self on public.employees; create policy emp_self on public.employees for select using(id=public.my_employee_id());
drop policy if exists prof_self on public.profiles; create policy prof_self on public.profiles for select using(id=auth.uid() or public.is_admin());
drop policy if exists prof_admin on public.profiles; create policy prof_admin on public.profiles for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists wr_admin on public.work_records; create policy wr_admin on public.work_records for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists wr_self_select on public.work_records; create policy wr_self_select on public.work_records for select using(employee_id=public.my_employee_id());
drop policy if exists wr_self_insert on public.work_records; create policy wr_self_insert on public.work_records for insert with check(employee_id=public.my_employee_id());
drop policy if exists wr_self_update on public.work_records; create policy wr_self_update on public.work_records for update using(employee_id=public.my_employee_id()) with check(employee_id=public.my_employee_id());
grant usage on schema public to authenticated; grant select,insert,update,delete on public.employees,public.profiles,public.work_records to authenticated;
